### ISSUE TITLE
[Request] PsionicCabal-Empire Merger

### ISSUE THREAD

**Issue by HappyHead** [kampangs/royaltypsitechmerger#1]
If there's any reasonable way for this to be done, I and whatever minority I represent would LOVE to see this. please please please please PLEASE! lol

I haven't gotten a chance to try this out yet, so some of this may be exactly what you did already and it's just not in the mod decription yet so please let me know if I'm just running my mouth XD

Are the following features in the mod already and if not can they be?

----------------------------------

1. Cut the Cabal and merge the Cabal's events to the Empire while giving the Empire full access to PsiTech's psionics

2. Cut Royalty's psi-gear from the game to avoid bloat and, where appropriate, mark PsiTech Gear as appropriate apparel for "royals", giving the Empire's pawns the Cabal's equipment where appropriate

3. Have PsiTech "interact" with Royalty's psylink advancement system by locking a pawn's ability to train for focus nodes and certain abilities behind their psylink level. (Letting Royal advancement ceremonies as well as Anima-Tree rituals still be important for psychic advancement)

4. Give meditation a use in PsiTech's systems, even if its as simple as lowering Psytech's default psi-energy regeneration rate and having meditation more quickly restore Psi-energy

**Comment by kampangs** [comment]
Hi, thank you for your feedback and enthusiasm.

1. I don't think the Cabal and Empire can be merged without effectively destroying one or the other. The Cabal is a purely hostile faction that's meant to discourage pursuing psionics. The Empire doesn't just give psylink; it is a usually-friendly faction that offers you various benefits (permits, spacer traders, persona weapons, etc.) in exchange for elevating at least one demanding noble. These faction roles require different goodwill settings, so the factions can't be merged.

2. I agree that there's probably too much psi-gear now. I might cut some of the royalty gear (not prestige armor, the clothing). I'm reluctant to cut prestige armor or PsiTech armor because they both have distinctive appearances that some people probably value. IIRC most PsiTech apparel is already accepted by noble colonists. I mostly don't want Royalty pawns to use PsiTech apparel or vice versa because I want them to look different.

3. I'm reluctant to directly alter PsiTech's balance in this mod. I do suspect psionics are probably overly abundant in PsiTech, but that view isn't tempered by experience, and if it's true I would rather there be changes in PsiTech itself so people without Royalty benefit.

4. This is another thing I don't want to do because it messes with PsiTech balance too much.

**Comment by HappyHead** [comment]
awww, well fair enough, Thanks for the reasoned reply!
